name: demo workflow
on: workflow_dispatch
jobs:
  print_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo hello gh actions!
      - name: print a few lines
        run: |
          echo first line
          echo second line
